[package]
name = "rust-numerico"
version = "0.1.0"
edition = "2024"

[dependencies]
integrate = "0.1.11"
kiss3d = "0.37.1"
nalgebra = "0.34.1"
ndarray = "0.17.1"
plotters = "0.3.7"
tokio = {version="1.48.0",features=["full"]}
